//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.SMSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:smsserver", ConfigurationName="SMSServiceReference.smsserverPortType")]
    public interface smsserverPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message SendSMSRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ClassLibrary.SMSServiceReference.SendSMSResponse SendSMS(ClassLibrary.SMSServiceReference.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message GetCreditRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ClassLibrary.SMSServiceReference.GetCreditResponse GetCredit(ClassLibrary.SMSServiceReference.GetCreditRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (37.130.202.188) of message GetStatusRequest does not match the default value (urn:smsserver)
        [System.ServiceModel.OperationContractAttribute(Action="GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ClassLibrary.SMSServiceReference.GetStatusResponse GetStatus(ClassLibrary.SMSServiceReference.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fromNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string toNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string pass;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(string fromNum, string toNum, string messageContent, string messageType, string user, string pass) {
            this.fromNum = fromNum;
            this.toNum = toNum;
            this.messageContent = messageContent;
            this.messageType = messageType;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredit", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pass;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCreditResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string batchid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] unique_ids;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(string user, string pass, string batchid, string[] unique_ids) {
            this.user = user;
            this.pass = pass;
            this.batchid = batchid;
            this.unique_ids = unique_ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="37.130.202.188", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsserverPortTypeChannel : ClassLibrary.SMSServiceReference.smsserverPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsserverPortTypeClient : System.ServiceModel.ClientBase<ClassLibrary.SMSServiceReference.smsserverPortType>, ClassLibrary.SMSServiceReference.smsserverPortType {
        
        public smsserverPortTypeClient() {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserverPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsserverPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassLibrary.SMSServiceReference.SendSMSResponse ClassLibrary.SMSServiceReference.smsserverPortType.SendSMS(ClassLibrary.SMSServiceReference.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string fromNum, string toNum, string messageContent, string messageType, string user, string pass) {
            ClassLibrary.SMSServiceReference.SendSMSRequest inValue = new ClassLibrary.SMSServiceReference.SendSMSRequest();
            inValue.fromNum = fromNum;
            inValue.toNum = toNum;
            inValue.messageContent = messageContent;
            inValue.messageType = messageType;
            inValue.user = user;
            inValue.pass = pass;
            ClassLibrary.SMSServiceReference.SendSMSResponse retVal = ((ClassLibrary.SMSServiceReference.smsserverPortType)(this)).SendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassLibrary.SMSServiceReference.GetCreditResponse ClassLibrary.SMSServiceReference.smsserverPortType.GetCredit(ClassLibrary.SMSServiceReference.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public string GetCredit(string user, string pass) {
            ClassLibrary.SMSServiceReference.GetCreditRequest inValue = new ClassLibrary.SMSServiceReference.GetCreditRequest();
            inValue.user = user;
            inValue.pass = pass;
            ClassLibrary.SMSServiceReference.GetCreditResponse retVal = ((ClassLibrary.SMSServiceReference.smsserverPortType)(this)).GetCredit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassLibrary.SMSServiceReference.GetStatusResponse ClassLibrary.SMSServiceReference.smsserverPortType.GetStatus(ClassLibrary.SMSServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public string GetStatus(string user, string pass, string batchid, string[] unique_ids) {
            ClassLibrary.SMSServiceReference.GetStatusRequest inValue = new ClassLibrary.SMSServiceReference.GetStatusRequest();
            inValue.user = user;
            inValue.pass = pass;
            inValue.batchid = batchid;
            inValue.unique_ids = unique_ids;
            ClassLibrary.SMSServiceReference.GetStatusResponse retVal = ((ClassLibrary.SMSServiceReference.smsserverPortType)(this)).GetStatus(inValue);
            return retVal.@return;
        }
    }
}
